export { persian, resolveOptions } from "./plugin.js";
export { persian as default } from "./plugin.js";

export type {
  PersianOptions,
  ResolvedPersianOptions,
  HtmlOptions,
  JalaliOptions,
  TextOptions,
  FontOptions,
  ResolvedFontOptions,
  FontLocalOptions,
  FontFamily,
  FontDisplay,
  ExperimentalOptions,
  LogicalPropertiesOptions,
  JalaliEngine,
  CalendarEngine,
  JalaliDate,
  DateInput,
  JalaliFormatToken,
  JalaliDateFormat,
  MonthNameLocale,
  FormatJalali,
  ToJalali,
  ToGregorian,
  IsLeapJalaliYear,
  GetMonthName,
  JalaliVirtualModule,
  ToPersianDigits,
  ToEnglishDigits,
  NormalizePersianText,
  TextVirtualModule,
  CurrencyUnit,
  CurrencyDigitMode,
  CurrencyFormatOptions,
  ToToman,
  ToRial,
  FormatCurrency,
  IsNationalCode,
  IsMobileNumber,
  NormalizeMobileNumber,
  ToNumberWords,
} from "./types.js";